name: Release Unity Package

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  UNITY_PACKAGE_NAME: MarumaCam-${{ github.ref_name }}.unitypackage
  ASSET_PATH: Assets/Marumasa/MarumaCam

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create unitypackage
        run: |
          docker compose run --rm -u $(id -u):$(id -g) unity-packager

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ${{ env.UNITY_PACKAGE_NAME }} --title "${{ github.ref_name }}" --generate-notes